### PR TITLE
Switch from model fixtures to factories

### PR DESCRIPTION
**Pull request by kristinalim**
#### Summary

Update tests to use factories instead of model fixtures.

#### Additional Details

I usually prefer factories over fixtures, because:

* They are easier to maintain.
* They create test records that more closely reflect how the current code would *probably* set up data.
* They also make it easier to isolate test records to examples and example groups that actually want them around.

One example for the last point is that tests for `Invoice.poll_unpaid!` and `Invoice.email_unpaid_once!` failed when I added another fixture for an unpaid invoice, because they do not expect another unpaid invoice in the database.

However, with these changes, the test suite would now create more invoices on the Lightning Charge API. I suppose this would move #11 higher in the priority queue.

#### Dependencies

This branch includes changes in PR #76.

**UPDATE:** This branch now also includes changes in PR #78.

### CODE REVIEW

**Comment by Sjors** [comment]
For some reason the tests are failing for me locally and Travis also seems unhappy.

Mostly `SMTP From address may not be blank: nil`. That suggest it's ignoring the mock env variables in `rails_helper.rb`.

> with these changes, the test suite would now create more invoices on the Lightning Charge API

The test suite shouldn't be calling any external URL. There's mocks in place to prevent that, e.g. `expect_any_instance_of(Invoice).to receive(:poll!).and_return true`. Are they broken?

**Comment by kristinalim** [comment]
> The test suite shouldn't be calling any external URL. There's mocks in place to prevent that, e.g. `expect_any_instance_of(Invoice).to receive(:poll!).and_return true`. Are they broken?

With this switch to factories, the tests also stop using `charge_invoice_id` values hard-coded in the fixtures, and they attempt to create real invoices in the configured Lightning Charge server for the environment because I didn't stub this. And I also un-stubbed polling for the invoice status.

Are the Lightning Charge server details which you sent me for `development` okay to use temporarily for `test`? I'm now having doubts... I have probably created a hundred or so invoices so far, which would expire less than a week from now. (Sorry about that.)

I will look into #11 next.

**Comment by Sjors** [comment]
@kristinalim it's fine if you use it for development (it's a good stress test), but don't add the API key to the source code please.

**Comment by Sjors** [comment]
#11 would be super useful, but I don't think you need it to repair the tests.

I see three options:
1. keep this PR open until #11 is done
2. subclass the Invoice objects created by test suite, so they don't make http requests
3. intercept the http requests in the test and return mock responses

I don't have a strong preference.

**Comment by kristinalim** [comment]
@Sjors Great, I suddenly got worried they create too many records on your server.

Don't worry, the API key is not in the source code. I will stop using your Lightning Charge server for development/test too - I've already set up a local instance.

**Comment by Sjors** [comment]
By the way, I accidentally killed my lightning node on that server yesterday, so the API calls probably returned nothing for a while. It should work again. But glad you have a local instance.

**Comment by kristinalim** [comment]
Regarding the SMTP error, I found out `ENV['FROM_EMAIL']` was still blank when the sender for Devise emails is configured in `config/initializers/devise.rb`. This wasn't an issue when we were still using fixtures because users records were being created without Devise callbacks, so no user confirmation emails were being sent.

After further investigating, I noticed that `spec_helper.rb` already loads the Rails application. The original setup of the two files leaves loading of the Rails application to `rails_helper.rb`.

I moved some code from `spec_helper.rb` to `rails_helper.rb`, which should make sure that `rails_helper.rb` is the one that loads the Rails application.

**Comment by kristinalim** [comment]
@Sjors With regard to getting tests to pass without a real Lightning Charge server:

1. I moved real communication with the Lightning Charge server into `LightningChargeClient`, and then created a mock client `LightningChargeMockClient` with the same interface. `LightningChargeInvoice#client_klass` says which client would be used.
2. Tests for creating and reading invoices, for both of these real and mock clients, have been added.
3. For Number 2, we now replay recorded HTTP communication with my local Lightning Charge server through the `vcr` gem. The URL, API token, and basic auth string (derived from API token) are filtered out - aside from avoiding sensitive information from being recorded, this would make tests pass even if environment variables in other test environments are different. Please see https://github.com/Sjors/matreon/pull/77/commits/96cab9cdbdc4da86bc1720d50e8449b2a2a077ba in particular.

The Travis build is green. :slightly_smiling_face: I'm happy for this to be merged if you are.

Thank you!

**Comment by kristinalim** [comment]
Hmm, realizing that this PR has gotten big. :woman_facepalming: I can split this into two PRs if needed.

**Comment by kristinalim** [comment]
I've rebased this branch over PR #78.

**Comment by Sjors** [comment]
Glad to see Travis is happy. I had to drop and reload the schema on my local RAILS_ENV=test db, but now it works.

**Pull request merged**
